# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='model.Category'),
        ),
    ]
