# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pois',
            field=models.ManyToManyField(to='model.Poi'),
        ),
    ]
