# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pois',
            field=models.ManyToManyField(blank=True, to='model.Poi'),
        ),
    ]
